import type { PoolClient } from "../db.js";

/**
 * Resolve approver specs (e.g. "role:finance-lead" or a direct "user:x@acme.co") to concrete
 * principal ids at hold-creation time (D9 / schema `approvers_snapshot`).
 */
async function resolveApprovers(
  client: PoolClient,
  tenant: string,
  specs: string[],
): Promise<string[]> {
  const ids = new Set<string>();
  for (const spec of specs) {
    if (spec.startsWith("role:")) {
      const role = spec.slice("role:".length);
      const { rows } = await client.query<{ id: string }>(
        "SELECT id FROM principals WHERE tenant_id = $1 AND $2 = ANY(roles)",
        [tenant, role],
      );
      for (const r of rows) ids.add(r.id);
    } else {
      ids.add(spec);
    }
  }
  return [...ids];
}

export interface CreateHoldInput {
  holdId: string;
  tenant: string;
  verdictEntryId: string;
  initiatingPrincipal: string;
  approverSpecs: string[];
  ttlMinutes: number;
}

/**
 * Insert a PENDING hold in the verdict transaction (SPEC 2.5). The hold id is generated by the
 * caller so it can be embedded in the VERDICT payload before the hold row is written.
 */
export async function createHold(client: PoolClient, input: CreateHoldInput): Promise<string> {
  const holdId = input.holdId;
  const snapshot = await resolveApprovers(client, input.tenant, input.approverSpecs);
  await client.query(
    `INSERT INTO holds
       (id, tenant_id, verdict_entry_id, status, approvers_snapshot, initiating_principal, ttl_at)
     VALUES ($1, $2, $3, 'PENDING', $4::jsonb, $5, now() + make_interval(mins => $6))`,
    [
      holdId,
      input.tenant,
      input.verdictEntryId,
      JSON.stringify(snapshot),
      input.initiatingPrincipal,
      input.ttlMinutes,
    ],
  );
  return holdId;
}
